[project]
name = "ai-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "websocket-client>=1.9.0",
    "temporalio>=1.8.0",
    "asyncpg>=0.29.0",
    "websockets>=12.0",
    "httpx>=0.27.0",
    "sqlalchemy>=2.0.45",
    "prefect>=3.6.7",
    "hyperliquid-python-sdk>=0.21.0",
    "loguru>=0.7.3",
    "psycopg2-binary>=2.9.11",
]
