server {
    listen 80;
    server_name localhost;

    resolver 8.8.8.8;

    location / {
        proxy_pass https://marketplace.dify.ai;
        proxy_ssl_server_name on;
        proxy_set_header Host marketplace.dify.ai;
    }

    location /plugins/download {
        if ($arg_unique_identifier ~* "^([^/]+)/([^:]+):(.*)$") {
            set $org $1;
            set $plugin $2;
            set $version $3;
            rewrite ^ /api/v1/plugins/$org/$plugin/$version/download? break;
        }

        proxy_pass https://marketplace.dify.ai;
        proxy_ssl_server_name on;
        proxy_set_header Host marketplace.dify.ai;
    }
}
